//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface FYHookClass : NSObject
{
    NSMutableArray *_selsArray;
}

@property(retain, nonatomic) NSMutableArray *selsArray; // @synthesize selsArray=_selsArray;
- (void).cxx_destruct;
- (id)containsHookClassSEL:(id)arg1;
- (void)addHookClassSEL:(id)arg1 sel:(SEL)arg2 options:(unsigned long long)arg3 block:(id)arg4;

@end

