//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface FYHookClassSEL : NSObject
{
    NSObject *_object;
    SEL __SEL;
    NSArray *_beforeSEL;
    NSArray *_afterSEL;
    NSArray *_insteadSEL;
}

+ (id)FYHookClassSEL:(SEL)arg1 options:(unsigned long long)arg2 block:(CDUnknownBlockType)arg3;
@property(copy) NSArray *insteadSEL; // @synthesize insteadSEL=_insteadSEL;
@property(copy) NSArray *afterSEL; // @synthesize afterSEL=_afterSEL;
@property(copy) NSArray *beforeSEL; // @synthesize beforeSEL=_beforeSEL;
@property(nonatomic) SEL _SEL; // @synthesize _SEL=__SEL;
@property(retain, nonatomic) NSObject *object; // @synthesize object=_object;
- (void).cxx_destruct;
- (_Bool)containsBlock:(id)arg1 options:(unsigned long long)arg2;
- (void)addBlock:(id)arg1 HookClassOptions:(unsigned long long)arg2;

@end

