//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface ViewController2 : UIViewController
{
}

- (void)viewDidLoad;
- (void)pop:(id)arg1;
- (void)push:(id)arg1;
- (void)dealloc;

@end

